import Head from "next/head";
import { Container } from "@/layouts/Container";
import { Input } from "@/components/Input";

import { AiOutlineSearch } from "react-icons/ai";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Input
            placeholder="Search for people here"
            type="string"
            label="Email"
            icon={
              <AiOutlineSearch className="w-5 h-5 text-theme-muted-dark dark:text-theme-muted-dark" />
            }
          />
        </Container>
      </main>
    </>
  );
}
